apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app-deployment
  labels:
    app: ai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
        - name: ai-app
          image: ronak1907/ai-app:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: ai-app-service
spec:
  type: LoadBalancer
  selector:
    app: ai-app
  ports:
    - port: 8501
      targetPort: 8501
